name: Fix My Streak
on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  backdate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Backdated Commits
        run: |
          git config --global user.name "sanidhya2068"
          git config --global user.email "sanidhyasinghrathore5@gmail.com"
          
          # Pehle file create ya update karo
          touch streak.txt
          
          # 22 July ka commit
          echo "22 July Fix" >> streak.txt
          git add streak.txt
          GIT_AUTHOR_DATE="2026-07-22 12:00:00" GIT_COMMITTER_DATE="2026-07-22 12:00:00" git commit -m "Fixing 22 July"
          
          # 23 July ka commit
          echo "23 July Fix" >> streak.txt
          git add streak.txt
          GIT_AUTHOR_DATE="2026-07-23 12:00:00" GIT_COMMITTER_DATE="2026-07-23 12:00:00" git commit -m "Fixing 23 July"
          
          # Force push to main branch
          git push origin HEAD:main --force
