name: Fix My Streak
on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  backdate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Backdated Commit
        run: |
          git config --global user.name "sanidhya2068"
          git config --global user.email "sanidhyasinghrathore5@gmail.com"
          
          # Nayi file create karo
          touch streak_fix.txt
          
          # Sirf Kal ka commit (29 July 2026)
          echo "July 29 Fix" >> streak_fix.txt
          git add streak_fix.txt
          GIT_AUTHOR_DATE="2026-07-29 12:00:00" GIT_COMMITTER_DATE="2026-07-29 12:00:00" git commit -m "Fixing July 29 Streak"
          
          # Safe push bina purana code delete kiye
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com{{ github.repository }}.git HEAD:main
