name: Streak Saver
on:
  workflow_dispatch:
jobs:
  backdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change Last Commit Date
        run: |
          git config user.name "sanidhya2068"
          git config user.email "sanidhyasinghrathore5@gmail.com"
          git commit --amend --no-edit --date="2026-07-02 12:00:00"
          git push origin main -f
